// autogenerated - your edits will be overwritten!
import 'dart:typed_data';
import 'package:dartz/dartz.dart';
import 'package:web3dart/web3dart.dart';
import 'package:web3_contract/web3_contract.dart';

const EMPTY_ABI = '''[]''';
final EthereumAddress _zeroAddr =
    EthereumAddress(Uint8List(20)..fillRange(0, 20, 0));
EthereumAddress _addrOrDefault(EthereumAddress addr) => addr ?? _zeroAddr;

class emptyContract {
  DeployedContract $contract;
  EthereumAddress get $addr => $contract.address;
  ContractAbi get $abi => $contract.abi;
  Web3Client $client;
  emptyContract(String address, this.$client)
      : $contract = DeployedContract(ContractAbi.fromJson(EMPTY_ABI, 'empty'),
            EthereumAddress.fromHex(address));
}
