// autogenerated - your edits will be overwritten!
import 'dart:io';
import 'dart:typed_data';
import 'package:dartz/dartz.dart';
import 'package:web3dart/web3dart.dart';
import 'package:web3_contract/web3_contract.dart';

const EMPTY_ABI = """[]
""";
final EthereumAddress _zeroAddr =
    EthereumAddress(Uint8List(20)..fillRange(0, 20, 0));
EthereumAddress _addrOrDefault(EthereumAddress addr) => addr ?? _zeroAddr;

class emptyContract {
  final ContractAbi $abi = ContractAbi.fromJson(EMPTY_ABI, "empty");
  EthereumAddress $addr;
  DeployedContract $contract;
  Web3Client $client;
  emptyContract(String address, this.$client) {
    $addr = EthereumAddress.fromHex(address);
    $contract = DeployedContract($abi, $addr);
  }
}
